In [31]:
import numpy as np
np.set_printoptions(
    suppress=True,      # 禁用科學記號（如 1e+05）
    precision=2,        # 小數點後 2 位
    linewidth=150,      # 每行最大字元數（預設 75，太小會換行）
    threshold=np.inf    # 顯示所有元素（避免中間用 ... 省略）
)
hcz1 = np.linspace(0, 0.95, 20).reshape(4, 5)
print(hcz1)

[[0.   0.05 0.1  0.15 0.2 ]
 [0.25 0.3  0.35 0.4  0.45]
 [0.5  0.55 0.6  0.65 0.7 ]
 [0.75 0.8  0.85 0.9  0.95]]


In [17]:
hcz2 = np.random.rand(1, 5)
print(hcz2)

[[0.92855255 0.23302191 0.18086619 0.13325548 0.5821202 ]]


In [20]:
print(hcz1+hcz2,"\n")
print(hcz1-hcz2,"\n")
print(hcz1*hcz2,"\n")
print(hcz1/hcz2,"\n")

[[0.92855255 0.28302191 0.28086619 0.28325548 0.7821202 ]
 [1.17855255 0.53302191 0.53086619 0.53325548 1.0321202 ]
 [1.42855255 0.78302191 0.78086619 0.78325548 1.2821202 ]
 [1.67855255 1.03302191 1.03086619 1.03325548 1.5321202 ]] 

[[-0.92855255 -0.18302191 -0.08086619  0.01674452 -0.3821202 ]
 [-0.67855255  0.06697809  0.16913381  0.26674452 -0.1321202 ]
 [-0.42855255  0.31697809  0.41913381  0.51674452  0.1178798 ]
 [-0.17855255  0.56697809  0.66913381  0.76674452  0.3678798 ]] 

[[0.         0.0116511  0.01808662 0.01998832 0.11642404]
 [0.23213814 0.06990657 0.06330317 0.05330219 0.26195409]
 [0.46427627 0.12816205 0.10851971 0.08661606 0.40748414]
 [0.69641441 0.18641753 0.15373626 0.11992993 0.55301419]] 

[[0.         0.21457209 0.55289494 1.12565731 0.34357165]
 [0.26923624 1.28743257 1.93513228 3.00175283 0.77303622]
 [0.53847249 2.36029304 3.31736962 4.87784835 1.20250078]
 [0.80770873 3.43315351 4.69960696 6.75394387 1.63196535]] 



In [21]:
tmp = [[2012, 538580.0, 49084.6, 244639.1, 244856.2],
[2013, 592963.2, 53028.1, 261951.6, 277983.5],
[2014, 643563.1, 55626.3, 277282.8, 310654.0],
[2015, 688858.2, 57774.6, 281338.9, 349744.7],
[2016, 746395.1, 60139.2, 295427.8, 390828.1],
[2017, 832035.9, 62099.5, 331580.5, 438355.9],
[2018, 919281.1, 64745.2, 364835.2, 489700.8],
[2019, 986515.2, 70473.6, 380670.6, 535371.0],
[2020, 1013567.0, 78030.9, 383562.4, 551973.7],
[2021, 1143669.7, 83085.5, 450904.5, 609679.7]]
hcz3 = np.array(tmp)
print (hcz3)


[[   2012.   538580.    49084.6  244639.1  244856.2]
 [   2013.   592963.2   53028.1  261951.6  277983.5]
 [   2014.   643563.1   55626.3  277282.8  310654. ]
 [   2015.   688858.2   57774.6  281338.9  349744.7]
 [   2016.   746395.1   60139.2  295427.8  390828.1]
 [   2017.   832035.9   62099.5  331580.5  438355.9]
 [   2018.   919281.1   64745.2  364835.2  489700.8]
 [   2019.   986515.2   70473.6  380670.6  535371. ]
 [   2020.  1013567.    78030.9  383562.4  551973.7]
 [   2021.  1143669.7   83085.5  450904.5  609679.7]]


In [27]:
year = hcz3[:, 0:1]   # 年份
hcz4 = hcz3[:, 2:3]   # 第一
hcz5 = hcz3[:, 3:4]   # 第二
hcz6 = hcz3[:, 4:5]   # 第三
sumG = hcz3[:, 1:2]   # 總值
gdp1 = np.round((hcz4 / sumG), 2)
gdp2 = np.round((hcz5 / sumG), 2)
gdp3 = np.round((hcz6 / sumG), 2)
print("佔比分別爲(12-21年)\n第一產業\n",gdp1,"\n第二產業\n",gdp2,"\n第三產業\n",gdp3)


佔比分別爲(12-21年)
第一產業
 [[0.09]
 [0.09]
 [0.09]
 [0.08]
 [0.08]
 [0.07]
 [0.07]
 [0.07]
 [0.08]
 [0.07]] 
第二產業
 [[0.45]
 [0.44]
 [0.43]
 [0.41]
 [0.4 ]
 [0.4 ]
 [0.4 ]
 [0.39]
 [0.38]
 [0.39]] 
第三產業
 [[0.45]
 [0.47]
 [0.48]
 [0.51]
 [0.52]
 [0.53]
 [0.53]
 [0.54]
 [0.54]
 [0.53]]


In [32]:
hcz7 = np.hstack((year, sumG, hcz4, gdp1, hcz5, gdp2, hcz6, gdp3))
print (hcz7)


[[   2012.    538580.     49084.6        0.09  244639.1        0.45  244856.2        0.45]
 [   2013.    592963.2    53028.1        0.09  261951.6        0.44  277983.5        0.47]
 [   2014.    643563.1    55626.3        0.09  277282.8        0.43  310654.         0.48]
 [   2015.    688858.2    57774.6        0.08  281338.9        0.41  349744.7        0.51]
 [   2016.    746395.1    60139.2        0.08  295427.8        0.4   390828.1        0.52]
 [   2017.    832035.9    62099.5        0.07  331580.5        0.4   438355.9        0.53]
 [   2018.    919281.1    64745.2        0.07  364835.2        0.4   489700.8        0.53]
 [   2019.    986515.2    70473.6        0.07  380670.6        0.39  535371.         0.54]
 [   2020.   1013567.     78030.9        0.08  383562.4        0.38  551973.7        0.54]
 [   2021.   1143669.7    83085.5        0.07  450904.5        0.39  609679.7        0.53]]


In [33]:
hcz8 = hcz7[5:10, :]
print (hcz8)

[[   2017.    832035.9    62099.5        0.07  331580.5        0.4   438355.9        0.53]
 [   2018.    919281.1    64745.2        0.07  364835.2        0.4   489700.8        0.53]
 [   2019.    986515.2    70473.6        0.07  380670.6        0.39  535371.         0.54]
 [   2020.   1013567.     78030.9        0.08  383562.4        0.38  551973.7        0.54]
 [   2021.   1143669.7    83085.5        0.07  450904.5        0.39  609679.7        0.53]]
