In [37]:
import numpy as np
np.set_printoptions(
    suppress=True,      # 禁用科學記號（如 1e+05）
    precision=2,        # 小數點後 2 位
    linewidth=150,      # 每行最大字元數（預設 75，太小會換行）
    threshold=np.inf    # 顯示所有元素（避免中間用 ... 省略）
)
hcz = np.genfromtxt('GDP.csv', delimiter=',', dtype=float, skip_header=0)
print(hcz)

[[   2016.   746395.1   60139.2  295427.8  390828.1]
 [   2020.  1013567.    78030.9  383562.4  551973.7]
 [   2012.   538580.    49084.6  244639.1  244856.2]
 [   2013.   592963.2   53028.1  261951.6  277983.5]
 [   2021.  1143669.7   83085.5  450904.5  609679.7]
 [   2014.   643563.1   55626.3  277282.8  310654. ]
 [   2015.   688858.2   57774.6  281338.9  349744.7]
 [   2019.   986515.2   70473.6  380670.6  535371. ]
 [   2017.   832035.9   62099.5  331580.5  438355.9]
 [   2018.   919281.1   64745.2  364835.2  489700.8]
 [   2019.   986515.2   70473.6  380670.6  535371. ]
 [   2021.  1143669.7   83085.5  450904.5  609679.7]]


In [38]:
hcz_index = np.argsort(hcz[:, 0])
hcz = hcz[hcz_index]
print(hcz)

[[   2012.   538580.    49084.6  244639.1  244856.2]
 [   2013.   592963.2   53028.1  261951.6  277983.5]
 [   2014.   643563.1   55626.3  277282.8  310654. ]
 [   2015.   688858.2   57774.6  281338.9  349744.7]
 [   2016.   746395.1   60139.2  295427.8  390828.1]
 [   2017.   832035.9   62099.5  331580.5  438355.9]
 [   2018.   919281.1   64745.2  364835.2  489700.8]
 [   2019.   986515.2   70473.6  380670.6  535371. ]
 [   2019.   986515.2   70473.6  380670.6  535371. ]
 [   2020.  1013567.    78030.9  383562.4  551973.7]
 [   2021.  1143669.7   83085.5  450904.5  609679.7]
 [   2021.  1143669.7   83085.5  450904.5  609679.7]]


In [39]:
hcz_unique_index = np.unique(hcz[:, 0], return_index=True)[1]
hcz = hcz[hcz_unique_index]
print(hcz)

[[   2012.   538580.    49084.6  244639.1  244856.2]
 [   2013.   592963.2   53028.1  261951.6  277983.5]
 [   2014.   643563.1   55626.3  277282.8  310654. ]
 [   2015.   688858.2   57774.6  281338.9  349744.7]
 [   2016.   746395.1   60139.2  295427.8  390828.1]
 [   2017.   832035.9   62099.5  331580.5  438355.9]
 [   2018.   919281.1   64745.2  364835.2  489700.8]
 [   2019.   986515.2   70473.6  380670.6  535371. ]
 [   2020.  1013567.    78030.9  383562.4  551973.7]
 [   2021.  1143669.7   83085.5  450904.5  609679.7]]


In [40]:
hcz_gdp = hcz[:, 1:]
rates_tmp = np.diff(hcz_gdp, axis=0) / hcz_gdp[:-1] * 100
rates_with_nan = np.full((rates_tmp.shape[0]+1, rates_tmp.shape[1]), np.nan)
rates_with_nan[1:, :] = rates_tmp
rates = np.column_stack((hcz[:, 0], rates_with_nan))
print(rates)

[[2012.       nan     nan     nan     nan]
 [2013.     10.1     8.03    7.08   13.53]
 [2014.      8.53    4.9     5.85   11.75]
 [2015.      7.04    3.86    1.46   12.58]
 [2016.      8.35    4.09    5.01   11.75]
 [2017.     11.47    3.26   12.24   12.16]
 [2018.     10.49    4.26   10.03   11.71]
 [2019.      7.31    8.85    4.34    9.33]
 [2020.      2.74   10.72    0.76    3.1 ]
 [2021.     12.84    6.48   17.56   10.45]]


In [41]:
data2 = np.column_stack((hcz, rates))
print(data2)

[[   2012.    538580.     49084.6   244639.1   244856.2     2012.          nan        nan        nan        nan]
 [   2013.    592963.2    53028.1   261951.6   277983.5     2013.        10.1        8.03       7.08      13.53]
 [   2014.    643563.1    55626.3   277282.8   310654.      2014.         8.53       4.9        5.85      11.75]
 [   2015.    688858.2    57774.6   281338.9   349744.7     2015.         7.04       3.86       1.46      12.58]
 [   2016.    746395.1    60139.2   295427.8   390828.1     2016.         8.35       4.09       5.01      11.75]
 [   2017.    832035.9    62099.5   331580.5   438355.9     2017.        11.47       3.26      12.24      12.16]
 [   2018.    919281.1    64745.2   364835.2   489700.8     2018.        10.49       4.26      10.03      11.71]
 [   2019.    986515.2    70473.6   380670.6   535371.      2019.         7.31       8.85       4.34       9.33]
 [   2020.   1013567.     78030.9   383562.4   551973.7     2020.         2.74      10.72       

In [56]:
hcz_sgdp = hcz[:, 1]
mean_gdp = np.nanmean(hcz_sgdp)
min_gdp = np.nanmin(hcz_sgdp)
max_gdp = np.nanmax(hcz_sgdp)
print(mean_gdp, max_gdp, min_gdp)
hcz_srate = rates[:,1]
mean_rate = np.nanmean(hcz_srate)
min_rate = np.nanmin(hcz_srate)
max_rate = np.nanmax(hcz_srate)
print("\n",mean_rate, max_rate, min_rate)

810542.85 1143669.7 538580.0

 8.763701332569227 12.836122328370985 2.742157444710436


In [57]:
max_gdp_index_hcz = np.nanargmax(hcz_gdpS)
row = hcz[max_gdp_index_hcz]
print(row)

[   2021.  1143669.7   83085.5  450904.5  609679.7]


In [58]:
min_gdp_index_hcz = np.nanargmin(hcz_gdpS)
row = hcz[min_gdp_index_hcz]
print(row)

[  2012.  538580.   49084.6 244639.1 244856.2]


In [59]:
index = np.where(hcz_srate > 10)[0]
years = hcz[index, 0]
print(years)

[2013. 2017. 2018. 2021.]


In [61]:
np.savetxt("./GDPSta.csv", data2,delimiter=',', fmt='%.2f')