In [98]:
import numpy as np

# 创建数组

In [99]:
array1 = np.array([1, 2, 3])
print("一维数组:\n", array1)

一维数组:
 [1 2 3]


In [100]:
array2 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]])
print("二维数组:\n", array2)

二维数组:
 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


## arange(等差)

In [101]:
array3 = np.arange(0, 1, 0.1, float)
print(array3)
array4 = np.arange(0, 1, 0.09, float)
print(array4)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.   0.09 0.18 0.27 0.36 0.45 0.54 0.63 0.72 0.81 0.9  0.99]


从start开始, 步长为step的一串数据, 终值小于设定stop

## linspace(等差)

In [102]:
array5 = np.linspace(0, 1, 50, float)
print(array5)
array6 = np.linspace(0, 1, 51, float)
print(array6)


[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2  0.22 0.24 0.26
 0.28 0.3  0.32 0.34 0.36 0.38 0.4  0.42 0.44 0.46 0.48 0.5  0.52 0.54
 0.56 0.58 0.6  0.62 0.64 0.66 0.68 0.7  0.72 0.74 0.76 0.78 0.8  0.82
 0.84 0.86 0.88 0.9  0.92 0.94 0.96 0.98 1.  ]


包含start, stop在内的num个数, 步长为(stop-start)/(num-1)

传入参数endpoint = false 可不包含stop

传入参数retstep = true 可返回算出的步长

## logspace(等比)

In [103]:
array7 = np.logspace(0, 2, 100, float)
print(array7)

[  1.           1.04761575   1.09749877   1.149757     1.20450354
   1.26185688   1.32194115   1.38488637   1.45082878   1.51991108
   1.59228279   1.66810054   1.7475284    1.83073828   1.91791026
   2.009233     2.10490414   2.20513074   2.3101297    2.42012826
   2.53536449   2.65608778   2.7825594    2.91505306   3.05385551
   3.19926714   3.35160265   3.51119173   3.67837977   3.85352859
   4.03701726   4.22924287   4.43062146   4.64158883   4.86260158
   5.09413801   5.33669923   5.59081018   5.85702082   6.13590727
   6.42807312   6.73415066   7.05480231   7.39072203   7.74263683
   8.11130831   8.49753436   8.90215085   9.32603347   9.77009957
  10.23531022  10.72267222  11.23324033  11.76811952  12.32846739
  12.91549665  13.53047775  14.17474163  14.84968262  15.55676144
  16.29750835  17.07352647  17.88649529  18.73817423  19.6304065
  20.56512308  21.5443469   22.5701972   23.64489413  24.77076356
  25.95024211  27.18588243  28.48035868  29.8364724   31.2571585
  32.7454916

In [ ]:
# 

# 数组属性

In [104]:
print("一维数组形状:", array1.shape)
print("数组元素类型:", array1.dtype)
print("数组元素个数:", array1.size)
print("元素存储空间(字节):", array1.itemsize)
print("数组维度:", array1.ndim)

一维数组形状: (3,)
数组元素类型: int64
数组元素个数: 3
元素存储空间(字节): 8
数组维度: 1


In [105]:
print("二维数组形状:", array2.shape)
print("数组元素类型:", array2.dtype)
print("数组元素个数:", array2.size)
print("元素存储空间(字节):", array2.itemsize)
print("数组维度:", array2.ndim)

二维数组形状: (4, 3)
数组元素类型: int64
数组元素个数: 12
元素存储空间(字节): 8
数组维度: 2


# 编辑数组属性

In [106]:
array2.shape = 3, 4
print(array2)

[[1 2 3 1]
 [2 3 1 2]
 [3 1 2 3]]


只能在元素总数相同的情况下改变形状